name: get_instance
description: A smart dependency injector to GetX™ framework.
version: 3.12.0
homepage: https://github.com/jonataslaw/getx

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  get_core:
    git:
      url: git://github.com/jonataslaw/getx.git
      path: packages/get_core
      ref: master
  
dev_dependencies:
  test: ">=1.0.0 <2.0.0"
  test_coverage: ">=0.4.3 <1.0.0"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
