name: get_rx
description: A set of powerful tools to provide reactive programming for the GetX™ framework.
version: 3.10.2
author:
homepage: https://github.com/jonataslaw/getx

environment:
  sdk: ">=2.7.0 <3.0.0"
 

dependencies:
  get_core:
    path: ../get_core
  get_instance:
    path: ../get_instance
  meta: ">=1.1.0 <2.0.0"
 

dev_dependencies:
  test: ">=1.0.0 <2.0.0"
  test_coverage: ">=0.4.3 <1.0.0"
  