name: get_rx
description: A set of powerful tools to provide reactive programming for the GetX™ framework.
version: 3.10.2
homepage: https://github.com/jonataslaw/getx

environment:
  sdk: ">=2.7.0 <3.0.0"
 

dependencies:
  get_core: ">=3.10.2 <4.0.0"
  get_instance: ">=3.10.2 <4.0.0"
  meta: ">=1.1.0 <2.0.0"
 

dev_dependencies:
  test: ">=1.0.0 <2.0.0"
  test_coverage: ">=0.4.3 <1.0.0"
  