name: benckmark
description: A new Flutter application showing different kinds of state management.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  get: 2.12.5-beta
  bloc: ^4.0.0
  equatable: ^1.0.2
  flutter_bloc: ^4.0.0
  flutter_mobx: ^0.3.6
  flutter_redux: ^0.6.0
  meta:
  mobx: ^0.4.0+1
  provider: ^4.0.1
  redux: ^4.0.0
  rxdart: ^0.23.1
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.3
  mobx_codegen: ^0.4.0+1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages